// Class: ReadBDT_VZ_Zll_BOOSTFinal_wdB
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_VZ_Zll_BOOSTFinal_wdB
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : fglessge
Date           : Tue Feb 22 11:52:22 2022
Host           : Linux cmsbuild12.cern.ch 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 13:27:39 CET 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /t3home/fglessge/CMSSW_10_1_0/src/Xbb/python
Training events: 16376
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
FatJet_Msoftdrop[Hbb_fjidx]   FatJet_Msoftdrop_Hbb_fjidx_   FatJet_Msoftdrop[Hbb_fjidx]   FatJet_Msoftdrop[Hbb_fjidx]                                     'D'    [60.0071029663,119.999855042]
FatJet_Pt[Hbb_fjidx]          FatJet_Pt_Hbb_fjidx_          FatJet_Pt[Hbb_fjidx]          FatJet_Pt[Hbb_fjidx]                                            'D'    [250.00289917,2251.53173828]
SA5                           SA5                           SA5                           SA5                                                             'D'    [-1,17]
FatJet_Pt[Hbb_fjidx]/V_pt     FatJet_Pt_Hbb_fjidx__D_V_pt   FatJet_Pt[Hbb_fjidx]/V_pt     FatJet_Pt[Hbb_fjidx]/V_pt                                       'D'    [0.100519642234,7.230697155]
(FatJet_deepTagMD_bbvsLight[Hbb_fjidx])>0.97 _FatJet_deepTagMD_bbvsLight_Hbb_fjidx___0.97 (FatJet_deepTagMD_bbvsLight[Hbb_fjidx])>0.97 (FatJet_deepTagMD_bbvsLight[Hbb_fjidx])>0.97                                                  'D'    [0,1]
abs(TVector2::Phi_mpi_pi(V_phi-FatJet_phi[Hbb_fjidx]))  abs_TVector2_Phi_mpi_pi_V_phi_M_FatJet_phi_Hbb_fjidx___ abs(TVector2::Phi_mpi_pi(V_phi-FatJet_phi[Hbb_fjidx]))  abs(TVector2::Phi_mpi_pi(V_phi-FatJet_phi[Hbb_fjidx]))                                                              'D'    [1.57057023048,3.14158821106]
(-99+(hJidx[0]>-1)*(99+H_mass))           __M_99_P__hJidx_0___M_1__T__99_P_H_mass__ (-99+(hJidx[0]>-1)*(99+H_mass))           (-99+(hJidx[0]>-1)*(99+H_mass))                                                         'D'    [-99,4622.24169922]
(-99+Alt$((hJidx[0]>-1)*(99+H_pt),0))           __M_99_P_Alt___hJidx_0___M_1__T__99_P_H_pt_,0__ (-99+Alt$((hJidx[0]>-1)*(99+H_pt),0))           (-99+Alt$((hJidx[0]>-1)*(99+H_pt),0))                                                               'D'    [-99,2075.82250977]
(-99+Alt$((hJidx[0]>-1)*(99+V_pt/H_pt),0))             __M_99_P_Alt___hJidx_0___M_1__T__99_P_V_pt_D_H_pt_,0__ (-99+Alt$((hJidx[0]>-1)*(99+V_pt/H_pt),0))             (-99+Alt$((hJidx[0]>-1)*(99+V_pt/H_pt),0))                                                                        'D'    [-99,36.5564079285]
(-99+Alt$((hJidx[0]>-1)*(99+abs(TVector2::Phi_mpi_pi(V_phi-H_phi))),0))            __M_99_P_Alt___hJidx_0___M_1__T__99_P_abs_TVector2_Phi_mpi_pi_V_phi_M_H_phi___,0__ (-99+Alt$((hJidx[0]>-1)*(99+abs(TVector2::Phi_mpi_pi(V_phi-H_phi))),0))            (-99+Alt$((hJidx[0]>-1)*(99+abs(TVector2::Phi_mpi_pi(V_phi-H_phi))),0))                                                                                                   'D'    [-99,3.14159250259]
(-99+Alt$((hJidx[0]>-1)*(99+max(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))           __M_99_P_Alt___hJidx_0___M_1__T__99_P_max_hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered__,0__ (-99+Alt$((hJidx[0]>-1)*(99+max(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))           (-99+Alt$((hJidx[0]>-1)*(99+max(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))                                                                                                               'D'    [-99,2187.90307617]
(-99+Alt$((hJidx[0]>-1)*(99+min(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))           __M_99_P_Alt___hJidx_0___M_1__T__99_P_min_hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered__,0__ (-99+Alt$((hJidx[0]>-1)*(99+min(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))           (-99+Alt$((hJidx[0]>-1)*(99+min(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))                                                                                                               'D'    [-99,1764.78894043]
(-99+Alt$((hJidx[0]>-1)*(99+hJets_FSRrecovered_dEta),0))           __M_99_P_Alt___hJidx_0___M_1__T__99_P_hJets_FSRrecovered_dEta_,0__ (-99+Alt$((hJidx[0]>-1)*(99+hJets_FSRrecovered_dEta),0))           (-99+Alt$((hJidx[0]>-1)*(99+hJets_FSRrecovered_dEta),0))                                                                                  'D'    [-99,4.72363376617]
(-99+Alt$((hJidx[0]>-1)*(99+Sum$(Jet_Pt>30&&abs(Jet_eta)<2.5&&(Jet_puId>6||Jet_Pt>50.0)&&Jet_jetId>4&&Jet_lepFilter&&Iteration$!=hJidx[0]&&Iteration$!=hJidx[1])),0))           __M_99_P_Alt___hJidx_0___M_1__T__99_P_Sum__Jet_Pt_30__abs_Jet_eta__2.5___Jet_puId_6__Jet_Pt_50.0___Jet_jetId_4__Jet_lepFilter__Iteration___hJidx_0___Iteration___hJidx_1___,0__ (-99+Alt$((hJidx[0]>-1)*(99+Sum$(Jet_Pt>30&&abs(Jet_eta)<2.5&&(Jet_puId>6||Jet_Pt>50.0)&&Jet_jetId>4&&Jet_lepFilter&&Iteration$!=hJidx[0]&&Iteration$!=hJidx[1])),0))           (-99+Alt$((hJidx[0]>-1)*(99+Sum$(Jet_Pt>30&&abs(Jet_eta)<2.5&&(Jet_puId>6||Jet_Pt>50.0)&&Jet_jetId>4&&Jet_lepFilter&&Iteration$!=hJidx[0]&&Iteration$!=hJidx[1])),0))                                                                                                                                                                                               'D'    [-99,8]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_VZ_Zll_BOOSTFinal_wdBNode
   
#ifndef BDT_VZ_Zll_BOOSTFinal_wdBNode__def
#define BDT_VZ_Zll_BOOSTFinal_wdBNode__def
   
class BDT_VZ_Zll_BOOSTFinal_wdBNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_VZ_Zll_BOOSTFinal_wdBNode ( BDT_VZ_Zll_BOOSTFinal_wdBNode* left,BDT_VZ_Zll_BOOSTFinal_wdBNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_VZ_Zll_BOOSTFinal_wdBNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_VZ_Zll_BOOSTFinal_wdBNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_VZ_Zll_BOOSTFinal_wdBNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_VZ_Zll_BOOSTFinal_wdBNode*   fLeft;     // pointer to the left daughter node
   BDT_VZ_Zll_BOOSTFinal_wdBNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_VZ_Zll_BOOSTFinal_wdBNode::~BDT_VZ_Zll_BOOSTFinal_wdBNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_VZ_Zll_BOOSTFinal_wdBNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_VZ_Zll_BOOSTFinal_wdBNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_VZ_Zll_BOOSTFinal_wdB : public IClassifierReader {

 public:

   // constructor
   ReadBDT_VZ_Zll_BOOSTFinal_wdB( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_VZ_Zll_BOOSTFinal_wdB" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "FatJet_Msoftdrop[Hbb_fjidx]", "FatJet_Pt[Hbb_fjidx]", "SA5", "FatJet_Pt[Hbb_fjidx]/V_pt", "(FatJet_deepTagMD_bbvsLight[Hbb_fjidx])>0.97", "abs(TVector2::Phi_mpi_pi(V_phi-FatJet_phi[Hbb_fjidx]))", "(-99+(hJidx[0]>-1)*(99+H_mass))", "(-99+Alt$((hJidx[0]>-1)*(99+H_pt),0))", "(-99+Alt$((hJidx[0]>-1)*(99+V_pt/H_pt),0))", "(-99+Alt$((hJidx[0]>-1)*(99+abs(TVector2::Phi_mpi_pi(V_phi-H_phi))),0))", "(-99+Alt$((hJidx[0]>-1)*(99+max(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))", "(-99+Alt$((hJidx[0]>-1)*(99+min(hJets_0_pt_FSRrecovered,hJets_1_pt_FSRrecovered)),0))", "(-99+Alt$((hJidx[0]>-1)*(99+hJets_FSRrecovered_dEta),0))", "(-99+Alt$((hJidx[0]>-1)*(99+Sum$(Jet_Pt>30&&abs(Jet_eta)<2.5&&(Jet_puId>6||Jet_Pt>50.0)&&Jet_jetId>4&&Jet_lepFilter&&Iteration$!=hJidx[0]&&Iteration$!=hJidx[1])),0))" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_VZ_Zll_BOOSTFinal_wdB() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_VZ_Zll_BOOSTFinal_wdBNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_VZ_Zll_BOOSTFinal_wdB::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_VZ_Zll_BOOSTFinal_wdBNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_VZ_Zll_BOOSTFinal_wdBNode*)current->GetRight();
         else current=(BDT_VZ_Zll_BOOSTFinal_wdBNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_VZ_Zll_BOOSTFinal_wdB::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.525161674363459);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469247,-99) , 
2, 3.66667, 1, 0, 0.754335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418558,-99) , 
0, 74.3046, 0, 0, 0.704379,-99) , 
NN(
0, 
0, 
-1, 3.0668, 0, -1, 0.25396,-99) , 
4, 0.047619, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.320227);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 105.72, 1, 1, 0.712125,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393052,-99) , 
13, 1.95238, 1, 0, 0.518764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260898,-99) , 
0, 68.587, 0, 0, 0.486862,-99) , 
4, 0.047619, 0, 0, 0.606598,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.207334);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.06695, 0, 1, 0.667331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488672,-99) , 
0, 105.72, 1, 0, 0.641864,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40416,-99) , 
0, 104.747, 1, 0, 0.493874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365476,-99) , 
0, 74.2962, 0, 0, 0.465197,-99) , 
4, 0.047619, 0, 0, 0.556584,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.180652);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.95238, 1, 1, 0.61214,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592716,-99) , 
NN(
0, 
0, 
-1, 77.1508, 0, -1, 0.438631,-99) , 
3, 0.820472, 1, 0, 0.458598,-99) , 
4, 0.047619, 0, 0, 0.537244,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.181605);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432691,-99) , 
6, 107.738, 1, 0, 0.602403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485404,-99) , 
11, 45.4723, 0, 0, 0.576424,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475306,-99) , 
5, 2.99202, 0, 0, 0.587744,-99) , 
NN(
0, 
0, 
-1, 0.675014, 1, -1, 0.434213,-99) , 
10, 440.394, 0, 0, 0.478541,-99) , 
6, 125.821, 1, 0, 0.535235,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.150058);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 452.722, 0, 1, 0.573105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434837,-99) , 
3, 1.25441, 1, 0, 0.559672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39673,-99) , 
0, 65.7353, 0, 0, 0.548412,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.129221);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 78.5037, 1, 1, 0.60045,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472258,-99) , 
0, 88.5747, 1, 0, 0.540052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342135,-99) , 
0, 77.1606, 0, 0, 0.481911,-99) , 
3, 0.965541, 1, 0, 0.508083,-99) , 
1, 440.625, 0, 0, 0.524911,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0888286);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 432.654, 0, 1, 0.5685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456963,-99) , 
13, 1.95238, 1, 0, 0.546528,-99) , 
NN(
0, 
0, 
-1, 4.71429, 1, -1, 0.475307,-99) , 
4, 0.047619, 0, 0, 0.511302,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.113403);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498594,-99) , 
0, 88.586, 1, 0, 0.605915,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430122,-99) , 
4, 0.047619, 0, 0, 0.490583,-99) , 
5, 2.99203, 0, 0, 0.565006,-99) , 
NN(
NN(
0, 
0, 
-1, 432.657, 0, 1, 0.524009,-99) , 
NN(
0, 
0, 
-1, 345.361, 0, -1, 0.402155,-99) , 
0, 77.1606, 0, 0, 0.496002,-99) , 
3, 0.922398, 1, 0, 0.517968,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.110837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 335.456, 0, 1, 0.603651,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460533,-99) , 
10, 265.364, 1, 0, 0.491268,-99) , 
5, 2.99203, 0, 0, 0.563742,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462106,-99) , 
8, 0.86066, 0, 0, 0.54477,-99) , 
NN(
0, 
0, 
-1, 1.14286, 0, -1, 0.463994,-99) , 
1, 440.628, 0, 0, 0.481451,-99) , 
3, 0.922398, 1, 0, 0.507621,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.125359);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 97.1638, 1, 1, 0.604779,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409947,-99) , 
0, 85.729, 0, 0, 0.496404,-99) , 
3, 1.03242, 1, 0, 0.54609,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428558,-99) , 
12, 0.899937, 1, 0, 0.516607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402084,-99) , 
7, 250.176, 0, 0, 0.501947,-99) , 
1, 345.314, 0, 0, 0.521116,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0639336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.047619, 0, 1, 0.592938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490217,-99) , 
1, 440.625, 0, 0, 0.501596,-99) , 
2, 3.04762, 0, 0, 0.513601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409978,-99) , 
5, 2.84207, 1, 0, 0.452932,-99) , 
2, 4.66667, 1, 0, 0.505699,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0732862);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.047619, 0, 1, 0.577383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449652,-99) , 
5, 2.84251, 0, 0, 0.515276,-99) , 
2, 3.04762, 0, 0, 0.523357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416377,-99) , 
11, 90.1171, 0, 0, 0.457915,-99) , 
2, 4.66667, 1, 0, 0.514865,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0911909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494685,-99) , 
0, 91.4299, 1, 0, 0.567402,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39202,-99) , 
10, 203.547, 0, 0, 0.47969,-99) , 
1, 292.718, 0, 0, 0.527772,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454512,-99) , 
2, 4.28571, 1, 0, 0.512613,-99) , 
NN(
0, 
0, 
-1, 85.7251, 0, -1, 0.45966,-99) , 
2, 1.14286, 0, 0, 0.491823,-99) , 
3, 0.922398, 1, 0, 0.503125,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.10366);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439185,-99) , 
6, 104.186, 1, 0, 0.507452,-99) , 
1, 432.654, 0, 0, 0.522648,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487175,-99) , 
6, 125.821, 0, 0, 0.514027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450859,-99) , 
13, 1.95238, 0, 0, 0.471993,-99) , 
0, 80.0054, 1, 0, 0.486226,-99) , 
4, 0.047619, 0, 0, 0.504723,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0527178);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497828,-99) , 
1, 351.362, 0, 0, 0.517536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435769,-99) , 
3, 1.277, 1, 0, 0.511086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430409,-99) , 
5, 2.46867, 0, 0, 0.506535,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0524256);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 112.483, 0, 1, 0.52237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451631,-99) , 
3, 1.277, 1, 0, 0.51679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444119,-99) , 
5, 2.46867, 0, 0, 0.512707,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0419634);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476079,-99) , 
0, 82.6056, 0, 0, 0.501155,-99) , 
0, 70.9057, 1, 0, 0.507281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446833,-99) , 
0, 65.7353, 0, 0, 0.503225,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0788721);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.870682, 1, 1, 0.574206,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445592,-99) , 
2, 3.33333, 0, 0, 0.486897,-99) , 
2, 1.42857, 1, 0, 0.521596,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473623,-99) , 
0, 91.8481, 0, 0, 0.494932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417859,-99) , 
0, 111.432, 1, 0, 0.488998,-99) , 
3, 0.922398, 1, 0, 0.499222,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0761215);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 94.2955, 0, 1, 0.532357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461583,-99) , 
0, 79.0577, 1, 0, 0.488773,-99) , 
4, 0.047619, 0, 0, 0.510879,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48951,-99) , 
5, 3.06682, 1, 0, 0.51632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378352,-99) , 
10, 336.601, 1, 0, 0.476916,-99) , 
0, 100.008, 1, 0, 0.502061,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0653064);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490454,-99) , 
11, 104.117, 0, 0, 0.510473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424275,-99) , 
12, 0.404611, 1, 0, 0.468924,-99) , 
7, 418.815, 1, 0, 0.503135,-99) , 
NN(
0, 
0, 
-1, 330.888, 0, -1, 0.460708,-99) , 
2, 4.66667, 1, 0, 0.497609,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0985235);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477398,-99) , 
0, 91.4544, 1, 0, 0.556703,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423604,-99) , 
0, 91.4479, 0, 0, 0.493731,-99) , 
3, 0.97194, 1, 0, 0.522205,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484325,-99) , 
1, 332.773, 0, 0, 0.506087,-99) , 
NN(
0, 
0, 
-1, 285.322, 0, -1, 0.447354,-99) , 
7, 418.815, 1, 0, 0.494606,-99) , 
5, 3.06682, 0, 0, 0.506979,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0745075);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482564,-99) , 
0, 100.006, 1, 0, 0.523332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449142,-99) , 
11, 34.5319, 1, 0, 0.485508,-99) , 
6, 85.789, 0, 0, 0.515631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461671,-99) , 
5, 2.46867, 0, 0, 0.512625,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0312546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 70.9057, 1, 1, 0.513681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457055,-99) , 
0, 65.7353, 0, 0, 0.509926,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0533128);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.047619, 0, 1, 0.551708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419301,-99) , 
10, 203.547, 0, 0, 0.481861,-99) , 
1, 292.718, 0, 0, 0.520018,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543667,-99) , 
NN(
0, 
0, 
-1, 1.95238, 1, -1, 0.48754,-99) , 
5, 2.7678, 1, 0, 0.495468,-99) , 
3, 0.922398, 1, 0, 0.503168,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0855479);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620189,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491903,-99) , 
3, 0.855407, 1, 0, 0.506512,-99) , 
11, 135.767, 0, 0, 0.518462,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591072,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432877,-99) , 
12, 0.641759, 1, 0, 0.477588,-99) , 
12, 2.24948, 0, 0, 0.494013,-99) , 
6, 125.821, 1, 0, 0.507965,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0688954);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599797,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470162,-99) , 
6, 104.407, 1, 0, 0.521962,-99) , 
11, 135.767, 0, 0, 0.530054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570222,-99) , 
NN(
0, 
0, 
-1, 506.805, 1, -1, 0.481352,-99) , 
12, 2.24948, 0, 0, 0.494158,-99) , 
6, 125.821, 1, 0, 0.514679,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0486026);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.04762, 0, 1, 0.522206,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443684,-99) , 
7, 330.888, 0, 0, 0.483706,-99) , 
2, 4.66667, 1, 0, 0.517145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471116,-99) , 
0, 65.7353, 0, 0, 0.514126,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0492028);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49563,-99) , 
7, 310.677, 1, 0, 0.514549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438537,-99) , 
0, 77.0789, 0, 0, 0.479368,-99) , 
6, 85.789, 0, 0, 0.507417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464211,-99) , 
5, 2.46867, 0, 0, 0.505003,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.082743);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.226153, 0, 1, 0.548321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458747,-99) , 
4, 0.047619, 0, 0, 0.493098,-99) , 
12, 0.431572, 1, 0, 0.517726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437884,-99) , 
6, 86.9174, 0, 0, 0.490014,-99) , 
6, 226.583, 0, 0, 0.499075,-99) , 
7, 315.252, 0, 0, 0.50917,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0645877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466991,-99) , 
0, 66.8222, 0, 0, 0.523133,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467534,-99) , 
6, 104.407, 1, 0, 0.5067,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466806,-99) , 
9, 2.84427, 1, 0, 0.481127,-99) , 
6, 125.821, 1, 0, 0.496117,-99) , 
0, 74.3034, 1, 0, 0.501573,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0588877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490477,-99) , 
0, 88.6032, 1, 0, 0.532563,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491578,-99) , 
10, 272.306, 1, 0, 0.515136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47426,-99) , 
3, 0.779679, 1, 0, 0.482269,-99) , 
7, 325.591, 0, 0, 0.496368,-99) , 
10, 445.501, 0, 0, 0.500883,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0476843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559314,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477858,-99) , 
5, 2.98142, 0, 0, 0.506286,-99) , 
0, 68.591, 1, 0, 0.511901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466899,-99) , 
5, 2.46867, 0, 0, 0.509399,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.079842);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469647,-99) , 
11, 103.244, 1, 0, 0.529987,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480887,-99) , 
6, 98.331, 1, 0, 0.512739,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460875,-99) , 
0, 91.4391, 0, 0, 0.485717,-99) , 
13, 1, 0, 0, 0.499489,-99) , 
6, 350.642, 0, 0, 0.504805,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.076391);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.91725, 1, 1, 0.551101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463236,-99) , 
0, 100.017, 1, 0, 0.529377,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486999,-99) , 
3, 0.9843, 0, 0, 0.513303,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424295,-99) , 
2, 0.238095, 1, 0, 0.471683,-99) , 
6, 86.4571, 0, 0, 0.501927,-99) , 
10, 336.601, 0, 0, 0.510048,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0523099);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496908,-99) , 
2, 2.33333, 0, 0, 0.532485,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4977,-99) , 
7, 310.677, 1, 0, 0.518122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473731,-99) , 
13, 1, 0, 0, 0.495234,-99) , 
6, 125.821, 0, 0, 0.504895,-99) , 
0, 108.576, 0, 0, 0.508017,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.070882);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593185,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420408,-99) , 
11, 80.8079, 1, 0, 0.510851,-99) , 
5, 2.76774, 1, 0, 0.527043,-99) , 
NN(
NN(
0, 
0, 
-1, 335.433, 0, 1, 0.533522,-99) , 
NN(
0, 
0, 
-1, 170.608, 0, -1, 0.484323,-99) , 
3, 0.95345, 1, 0, 0.50529,-99) , 
10, 336.601, 0, 0, 0.511717,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0464998);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 45.0466, 1, 1, 0.518581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413862,-99) , 
6, 157.949, 1, 0, 0.473944,-99) , 
2, 4.71429, 1, 0, 0.513422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474436,-99) , 
5, 2.46867, 0, 0, 0.511244,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0315469);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 112.928, 1, 1, 0.524156,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489735,-99) , 
12, 1.35039, 1, 0, 0.524204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414479,-99) , 
3, 1.19453, 1, 0, 0.49409,-99) , 
6, 350.642, 0, 0, 0.499381,-99) , 
0, 108.576, 0, 0, 0.502175,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0586693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.33333, 0, 1, 0.549775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456568,-99) , 
10, 358.185, 0, 0, 0.519114,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537687,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475591,-99) , 
0, 100.008, 0, 0, 0.487607,-99) , 
11, 138.441, 0, 0, 0.492244,-99) , 
6, 350.642, 0, 0, 0.496896,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0663147);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476434,-99) , 
0, 66.8222, 0, 0, 0.519884,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459052,-99) , 
11, 93.3215, 0, 0, 0.521293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466818,-99) , 
11, 78.5037, 1, 0, 0.487685,-99) , 
2, 3.66667, 0, 0, 0.496033,-99) , 
0, 74.3034, 1, 0, 0.500815,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0315399);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531363,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489099,-99) , 
11, 93.3215, 0, 0, 0.516588,-99) , 
NN(
0, 
0, 
-1, 2.84251, 0, -1, 0.490832,-99) , 
2, 3.66667, 0, 0, 0.497068,-99) , 
0, 68.5914, 1, 0, 0.500623,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0470839);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 270.883, 1, 1, 0.528581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478406,-99) , 
0, 85.7275, 1, 0, 0.496621,-99) , 
7, 344.661, 0, 0, 0.508183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470681,-99) , 
7, 522.378, 1, 0, 0.505693,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0547823);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481873,-99) , 
11, 93.3215, 0, 0, 0.528509,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489778,-99) , 
11, 45.0466, 1, 0, 0.500673,-99) , 
2, 3.66667, 0, 0, 0.507646,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487457,-99) , 
10, 286.225, 1, 0, 0.513126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438345,-99) , 
0, 72.2609, 1, 0, 0.489898,-99) , 
0, 77.1595, 0, 0, 0.503268,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0620832);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49992,-99) , 
3, 0.985608, 0, 0, 0.530744,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448057,-99) , 
0, 83.28, 0, 0, 0.505876,-99) , 
10, 227.7, 1, 0, 0.514149,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473514,-99) , 
2, 1.42857, 0, 0, 0.514341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447609,-99) , 
11, 78.5037, 1, 0, 0.493509,-99) , 
0, 77.1595, 0, 0, 0.509062,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0355241);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 104.117, 0, 1, 0.514236,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432518,-99) , 
1, 442.643, 0, 0, 0.48514,-99) , 
7, 418.815, 1, 0, 0.50908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457177,-99) , 
7, 330.888, 0, 0, 0.481159,-99) , 
2, 4.66667, 1, 0, 0.505507,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.076828);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484115,-99) , 
0, 66.823, 0, 0, 0.532538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474873,-99) , 
10, 227.7, 1, 0, 0.493712,-99) , 
0, 74.3041, 1, 0, 0.502293,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451597,-99) , 
10, 321.093, 0, 0, 0.514637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423002,-99) , 
9, 2.99616, 1, 0, 0.48477,-99) , 
13, 1.95238, 1, 0, 0.498662,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0763859);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495675,-99) , 
2, 1.42857, 1, 0, 0.530331,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435533,-99) , 
13, 0.333333, 0, 0, 0.491864,-99) , 
8, 0.997909, 0, 0, 0.509605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456534,-99) , 
2, 2.09524, 0, 0, 0.473856,-99) , 
10, 212.111, 0, 0, 0.488882,-99) , 
10, 227.7, 0, 0, 0.50297,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0297362);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454849,-99) , 
6, 412.383, 1, 0, 0.504057,-99) , 
10, 483.967, 0, 0, 0.507519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474929,-99) , 
3, 1.25441, 1, 0, 0.50424,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.063097);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419482,-99) , 
9, 2.99753, 1, 0, 0.489785,-99) , 
5, 2.99202, 0, 0, 0.523852,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472692,-99) , 
10, 197.514, 0, 0, 0.502313,-99) , 
NN(
0, 
0, 
-1, 0.534387, 1, -1, 0.469003,-99) , 
10, 316.156, 1, 0, 0.494149,-99) , 
6, 350.642, 0, 0, 0.499246,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0532439);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561543,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43525,-99) , 
9, 2.99753, 1, 0, 0.489284,-99) , 
5, 2.99202, 0, 0, 0.517488,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472938,-99) , 
4, 0.047619, 0, 0, 0.514526,-99) , 
NN(
0, 
0, 
-1, 1.19453, 1, -1, 0.486143,-99) , 
11, 98.8679, 0, 0, 0.494401,-99) , 
6, 350.642, 0, 0, 0.498352,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0230628);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498743,-99) , 
10, 160.183, 1, 0, 0.503975,-99) , 
10, 445.501, 0, 0, 0.508477,-99) , 
NN(
0, 
0, 
-1, 1.05538, 1, -1, 0.48061,-99) , 
2, 4.66667, 1, 0, 0.504917,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0317256);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 44.3359, 1, 1, 0.514891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478068,-99) , 
3, 1.25441, 1, 0, 0.511546,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460045,-99) , 
3, 1.05538, 1, 0, 0.486464,-99) , 
2, 4.66667, 1, 0, 0.508343,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.06568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.84249, 1, 1, 0.529573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4484,-99) , 
0, 102.871, 1, 0, 0.513806,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487765,-99) , 
7, 344.398, 0, 0, 0.517046,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446918,-99) , 
7, 290.034, 1, 0, 0.481953,-99) , 
11, 85.3112, 0, 0, 0.497772,-99) , 
10, 336.601, 0, 0, 0.50249,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0388853);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489208,-99) , 
7, 314.794, 1, 0, 0.525814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493687,-99) , 
1, 432.654, 0, 0, 0.501142,-99) , 
0, 85.3203, 1, 0, 0.506777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480932,-99) , 
2, 2.2381, 1, 0, 0.500517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445023,-99) , 
0, 72.2609, 1, 0, 0.483083,-99) , 
0, 77.1595, 0, 0, 0.500944,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0460741);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485787,-99) , 
3, 0.827462, 0, 0, 0.514666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482439,-99) , 
3, 1.25441, 1, 0, 0.511497,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468187,-99) , 
2, 1.42857, 0, 0, 0.499252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450952,-99) , 
11, 78.5037, 1, 0, 0.484173,-99) , 
0, 77.1595, 0, 0, 0.504774,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0308632);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462424,-99) , 
12, 1.79963, 1, 0, 0.506705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471922,-99) , 
7, 226.352, 0, 0, 0.503389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467734,-99) , 
7, 522.378, 1, 0, 0.501013,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0335597);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478308,-99) , 
4, 0.047619, 0, 0, 0.518258,-99) , 
NN(
0, 
0, 
-1, 107.758, 1, -1, 0.494788,-99) , 
2, 3.66667, 0, 0, 0.500654,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511098,-99) , 
NN(
0, 
0, 
-1, 68.9916, 1, -1, 0.461915,-99) , 
2, 1.42857, 1, 0, 0.484928,-99) , 
0, 77.1595, 0, 0, 0.496788,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0388538);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 293.842, 0, 1, 0.528428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469492,-99) , 
5, 2.98138, 0, 0, 0.503685,-99) , 
5, 2.76774, 1, 0, 0.507133,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466339,-99) , 
0, 68.9975, 1, 0, 0.485513,-99) , 
0, 77.1595, 0, 0, 0.50182,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0345581);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494421,-99) , 
11, 104.117, 0, 0, 0.504368,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457836,-99) , 
12, 0.404611, 1, 0, 0.481828,-99) , 
7, 418.815, 1, 0, 0.500362,-99) , 
NN(
0, 
0, 
-1, 286.225, 0, -1, 0.477891,-99) , 
2, 4.66667, 1, 0, 0.497494,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.062174);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495791,-99) , 
12, 0.450312, 1, 0, 0.529946,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409551,-99) , 
12, 0.217194, 0, 0, 0.486458,-99) , 
8, 0.997909, 0, 0, 0.50649,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479698,-99) , 
0, 99.6043, 1, 0, 0.518668,-99) , 
NN(
0, 
0, 
-1, 3.06848, 0, -1, 0.471021,-99) , 
0, 91.4403, 0, 0, 0.491746,-99) , 
10, 227.7, 0, 0, 0.501762,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0364541);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474991,-99) , 
6, 83.7541, 0, 0, 0.501555,-99) , 
3, 0.774653, 1, 0, 0.507075,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450263,-99) , 
4, 0.047619, 0, 0, 0.483749,-99) , 
7, 418.815, 1, 0, 0.502764,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.060673);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529319,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477843,-99) , 
10, 271.53, 0, 0, 0.504524,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463953,-99) , 
10, 241.553, 1, 0, 0.47858,-99) , 
8, 0.943984, 0, 0, 0.495634,-99) , 
7, 108.126, 1, 0, 0.497903,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0439469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473291,-99) , 
2, 3.28571, 1, 0, 0.498681,-99) , 
3, 0.774653, 1, 0, 0.503935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448159,-99) , 
0, 84.7983, 0, 0, 0.502399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442665,-99) , 
0, 100.017, 1, 0, 0.484126,-99) , 
7, 418.815, 1, 0, 0.500273,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0632499);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482922,-99) , 
11, 108.241, 1, 0, 0.514101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463266,-99) , 
1, 440.625, 1, 0, 0.504584,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485608,-99) , 
11, 31.601, 1, 0, 0.511635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440558,-99) , 
0, 91.4479, 0, 0, 0.47368,-99) , 
3, 0.97194, 1, 0, 0.490523,-99) , 
5, 2.99205, 1, 0, 0.495442,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0425064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45815,-99) , 
3, 1.06883, 1, 0, 0.498259,-99) , 
5, 2.91727, 1, 0, 0.507495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536921,-99) , 
NN(
0, 
0, 
-1, 1.2381, 0, -1, 0.48296,-99) , 
2, -0.333333, 1, 0, 0.488817,-99) , 
0, 88.5836, 1, 0, 0.497969,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0336108);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493254,-99) , 
2, 2.33333, 0, 0, 0.519975,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492225,-99) , 
0, 97.6761, 0, 0, 0.499887,-99) , 
NN(
0, 
0, 
-1, 338.34, 1, -1, 0.471941,-99) , 
0, 101.64, 1, 0, 0.496347,-99) , 
0, 108.576, 0, 0, 0.499059,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0741547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539242,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447399,-99) , 
6, 99.6743, 1, 0, 0.501795,-99) , 
6, 222.036, 0, 0, 0.511027,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484321,-99) , 
1, 338.192, 1, 0, 0.530427,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426887,-99) , 
0, 92.3658, 1, 0, 0.487742,-99) , 
0, 99.9874, 0, 0, 0.498832,-99) , 
4, 0.047619, 0, 0, 0.505154,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.040061);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496714,-99) , 
11, 93.3215, 0, 0, 0.52807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492541,-99) , 
10, 445.501, 0, 0, 0.497069,-99) , 
2, 3.66667, 0, 0, 0.504805,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459983,-99) , 
2, 1.42857, 0, 0, 0.489471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455624,-99) , 
11, 78.5037, 1, 0, 0.478965,-99) , 
0, 77.1595, 0, 0, 0.498488,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0392448);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 85.3283, 1, 1, 0.516823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453617,-99) , 
1, 329.63, 0, 0, 0.486631,-99) , 
2, 0.333333, 0, 0, 0.510934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503285,-99) , 
NN(
0, 
0, 
-1, 68.9916, 1, -1, 0.463192,-99) , 
2, 1.42857, 1, 0, 0.481994,-99) , 
0, 77.1595, 0, 0, 0.503864,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0552284);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 112.928, 1, 1, 0.523113,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423692,-99) , 
12, 1.05337, 1, 0, 0.505116,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471055,-99) , 
6, 252.116, 0, 0, 0.486092,-99) , 
11, 78.5037, 0, 0, 0.494656,-99) , 
0, 108.576, 0, 0, 0.497923,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0499324);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 105.714, 0, 1, 0.520097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465144,-99) , 
5, 3.03481, 1, 0, 0.485144,-99) , 
3, 0.954472, 1, 0, 0.498709,-99) , 
NN(
0, 
0, 
-1, 3.04762, 0, -1, 0.474054,-99) , 
5, 2.69297, 0, 0, 0.496029,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0371534);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480794,-99) , 
4, 0.047619, 0, 0, 0.494855,-99) , 
6, 85.789, 1, 0, 0.498471,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466231,-99) , 
2, 1.42857, 0, 0, 0.494353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457011,-99) , 
11, 78.5037, 1, 0, 0.48281,-99) , 
0, 77.1595, 0, 0, 0.494646,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0428879);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440154,-99) , 
5, 3.08464, 0, 0, 0.505294,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463574,-99) , 
1, 345.314, 1, 0, 0.487658,-99) , 
5, 3.06682, 0, 0, 0.496152,-99) , 
NN(
0, 
0, 
-1, 286.225, 0, -1, 0.479633,-99) , 
2, 4.66667, 1, 0, 0.494047,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0485306);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563017,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425444,-99) , 
11, 80.8079, 1, 0, 0.485967,-99) , 
5, 2.76774, 1, 0, 0.500578,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424399,-99) , 
12, 0.899937, 1, 0, 0.495668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440881,-99) , 
7, 244.23, 0, 0, 0.487997,-99) , 
10, 336.601, 0, 0, 0.491697,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0453891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506199,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46776,-99) , 
0, 80.0041, 1, 0, 0.497949,-99) , 
NN(
0, 
0, 
-1, 77.1595, 0, -1, 0.47912,-99) , 
11, 40.8365, 1, 0, 0.483746,-99) , 
6, 575.463, 0, 0, 0.485342,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0404609);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488977,-99) , 
10, 303.624, 0, 0, 0.518573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484107,-99) , 
1, 432.654, 0, 0, 0.489953,-99) , 
2, 3.66667, 0, 0, 0.497056,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475635,-99) , 
10, 286.225, 1, 0, 0.490738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455543,-99) , 
0, 72.2609, 1, 0, 0.479752,-99) , 
0, 77.1595, 0, 0, 0.492829,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0443099);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496165,-99) , 
1, 323.26, 1, 0, 0.519587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471923,-99) , 
10, 336.601, 1, 0, 0.496289,-99) , 
2, 3.66667, 0, 0, 0.502068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412554,-99) , 
10, 251.364, 0, 0, 0.467995,-99) , 
10, 333.858, 0, 0, 0.482324,-99) , 
0, 77.1595, 0, 0, 0.497246,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0302354);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494621,-99) , 
10, 303.624, 0, 0, 0.520762,-99) , 
NN(
0, 
0, 
-1, 117.07, 1, -1, 0.49104,-99) , 
2, 3.66667, 0, 0, 0.498409,-99) , 
NN(
0, 
0, 
-1, 1.42857, 1, -1, 0.479406,-99) , 
0, 77.1595, 0, 0, 0.493773,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0298334);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495296,-99) , 
4, 0.047619, 0, 0, 0.521513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475851,-99) , 
11, 117.07, 1, 0, 0.498676,-99) , 
2, 3.66667, 0, 0, 0.504336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505365,-99) , 
NN(
0, 
0, 
-1, 68.9916, 1, -1, 0.470722,-99) , 
2, 1.42857, 1, 0, 0.487001,-99) , 
0, 77.1595, 0, 0, 0.500108,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0391942);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 303.624, 0, 1, 0.521585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483895,-99) , 
5, 3.06682, 0, 0, 0.494687,-99) , 
2, 3.66667, 0, 0, 0.501351,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509303,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429223,-99) , 
10, 251.364, 0, 0, 0.476525,-99) , 
10, 333.858, 0, 0, 0.487462,-99) , 
0, 77.1595, 0, 0, 0.497964,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0282285);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4988,-99) , 
0, 109.803, 0, 0, 0.506973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466223,-99) , 
1, 341.328, 0, 0, 0.485103,-99) , 
2, 1.66667, 0, 0, 0.498787,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503053,-99) , 
NN(
0, 
0, 
-1, 2.2381, 1, -1, 0.475119,-99) , 
7, 278.969, 1, 0, 0.48486,-99) , 
0, 77.1595, 0, 0, 0.495393,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0431013);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 111.432, 0, 1, 0.509671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452438,-99) , 
11, 166.887, 1, 0, 0.504455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524868,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467221,-99) , 
3, 0.858078, 1, 0, 0.481581,-99) , 
5, 2.99276, 1, 0, 0.489045,-99) , 
2, 1.42857, 0, 0, 0.498327,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0467372);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478296,-99) , 
13, 0.333333, 0, 0, 0.503073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429892,-99) , 
2, 2.33333, 1, 0, 0.481678,-99) , 
11, 45.0466, 0, 0, 0.498555,-99) , 
NN(
0, 
0, 
-1, 1.42857, 1, -1, 0.482588,-99) , 
0, 77.1595, 0, 0, 0.494671,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0421848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493839,-99) , 
0, 80.0157, 1, 0, 0.504719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460315,-99) , 
5, 2.84251, 0, 0, 0.500063,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530603,-99) , 
NN(
0, 
0, 
-1, 314.543, 0, -1, 0.451598,-99) , 
12, 0.421624, 1, 0, 0.48117,-99) , 
13, 1.95238, 1, 0, 0.49617,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0335418);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.0277, 1, 1, 0.508264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470852,-99) , 
5, 2.84251, 0, 0, 0.504345,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484733,-99) , 
11, 77.4208, 1, 0, 0.512324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438611,-99) , 
7, 314.543, 0, 0, 0.483819,-99) , 
13, 1.95238, 1, 0, 0.50012,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0407239);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494517,-99) , 
2, 3.33333, 0, 0, 0.505006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442965,-99) , 
2, 2.33333, 1, 0, 0.480571,-99) , 
11, 45.0466, 0, 0, 0.499854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503942,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429759,-99) , 
6, 86.4571, 0, 0, 0.471418,-99) , 
10, 333.858, 0, 0, 0.48228,-99) , 
0, 77.1595, 0, 0, 0.495581,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0398997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473924,-99) , 
12, 1.12159, 1, 0, 0.510094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45838,-99) , 
0, 99.5816, 0, 0, 0.478709,-99) , 
11, 45.0466, 0, 0, 0.50348,-99) , 
NN(
0, 
0, 
-1, 1.42857, 1, -1, 0.479503,-99) , 
0, 77.1595, 0, 0, 0.497653,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0245282);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49209,-99) , 
10, 160.183, 1, 0, 0.495982,-99) , 
10, 445.501, 0, 0, 0.498749,-99) , 
NN(
0, 
0, 
-1, 2.84207, 1, -1, 0.477166,-99) , 
2, 4.66667, 1, 0, 0.496021,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0393598);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468487,-99) , 
7, 315.084, 0, 0, 0.526741,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491216,-99) , 
11, 140.813, 0, 0, 0.497697,-99) , 
5, 2.76774, 1, 0, 0.501536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471779,-99) , 
7, 522.378, 1, 0, 0.499581,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0543845);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483388,-99) , 
0, 66.823, 0, 0, 0.526929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490963,-99) , 
7, 315.252, 1, 0, 0.505367,-99) , 
0, 74.3041, 1, 0, 0.510065,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40175,-99) , 
0, 97.1516, 0, 0, 0.464596,-99) , 
10, 321.093, 0, 0, 0.492878,-99) , 
13, 1.95238, 1, 0, 0.506537,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0420126);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.0277, 1, 1, 0.513211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486318,-99) , 
5, 2.84251, 0, 0, 0.510408,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463468,-99) , 
10, 321.093, 0, 0, 0.508173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444642,-99) , 
9, 2.99616, 1, 0, 0.487565,-99) , 
13, 1.95238, 1, 0, 0.505726,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0456712);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482365,-99) , 
10, 333.858, 0, 0, 0.51907,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489885,-99) , 
5, 3.03478, 1, 0, 0.502516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404801,-99) , 
5, 3.01718, 0, 0, 0.461964,-99) , 
3, 1.17772, 1, 0, 0.497004,-99) , 
5, 2.76774, 1, 0, 0.49999,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0309154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493805,-99) , 
10, 333.858, 0, 0, 0.520939,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49796,-99) , 
11, 112.483, 0, 0, 0.506208,-99) , 
NN(
0, 
0, 
-1, 3.01718, 0, -1, 0.460776,-99) , 
3, 1.17772, 1, 0, 0.500041,-99) , 
5, 2.76774, 1, 0, 0.502866,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0442101);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467936,-99) , 
5, 3.08464, 0, 0, 0.516332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44387,-99) , 
0, 71.4475, 0, 0, 0.504396,-99) , 
5, 3.06682, 0, 0, 0.510155,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47617,-99) , 
5, 2.84207, 1, 0, 0.48743,-99) , 
2, 4.66667, 1, 0, 0.507306,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0496379);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484849,-99) , 
2, 2.57143, 1, 0, 0.507619,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439784,-99) , 
7, 279.516, 1, 0, 0.491558,-99) , 
7, 300.651, 0, 0, 0.502551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481338,-99) , 
7, 211.689, 0, 0, 0.500769,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0450309);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480012,-99) , 
5, 2.48283, 0, 0, 0.514698,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495345,-99) , 
5, 3.0348, 1, 0, 0.504507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423711,-99) , 
5, 2.89999, 1, 0, 0.471236,-99) , 
5, 2.98138, 0, 0, 0.497086,-99) , 
5, 2.76774, 1, 0, 0.49946,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0475038);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 194.171, 1, 1, 0.533528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465285,-99) , 
10, 258.852, 0, 0, 0.497368,-99) , 
3, 0.97194, 1, 0, 0.513857,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463461,-99) , 
1, 440.625, 1, 0, 0.501755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461923,-99) , 
0, 71.4474, 0, 0, 0.496365,-99) , 
5, 3.06682, 0, 0, 0.504218,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.036473);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495548,-99) , 
3, 0.97194, 1, 0, 0.515452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477998,-99) , 
0, 102.868, 1, 0, 0.508226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460729,-99) , 
6, 157.949, 1, 0, 0.486344,-99) , 
10, 445.501, 0, 0, 0.491057,-99) , 
5, 3.06682, 0, 0, 0.498762,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0534636);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484437,-99) , 
1, 308.671, 0, 0, 0.522827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45894,-99) , 
11, 57.7211, 1, 0, 0.493957,-99) , 
0, 85.738, 0, 0, 0.510565,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479009,-99) , 
0, 88.5806, 1, 0, 0.49489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418597,-99) , 
3, 0.95345, 0, 0, 0.467237,-99) , 
10, 227.7, 0, 0, 0.487801,-99) , 
5, 3.06682, 0, 0, 0.498016,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_VZ_Zll_BOOSTFinal_wdB::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_VZ_Zll_BOOSTFinal_wdB::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
